version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DOMAIN=todoenbici.org
      - PORT=80
    expose:
      - 80

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /Users/kbs/git/ecommers-bici:/usr/share/nginx/html
    depends_on:
      - app
